// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/mock_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	storage "agent-management/server/internal/storage"
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRepository is a mock of AgentRepository interface.
type MockAgentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRepositoryMockRecorder
	isgomock struct{}
}

// MockAgentRepositoryMockRecorder is the mock recorder for MockAgentRepository.
type MockAgentRepositoryMockRecorder struct {
	mock *MockAgentRepository
}

// NewMockAgentRepository creates a new mock instance.
func NewMockAgentRepository(ctrl *gomock.Controller) *MockAgentRepository {
	mock := &MockAgentRepository{ctrl: ctrl}
	mock.recorder = &MockAgentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRepository) EXPECT() *MockAgentRepositoryMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockAgentRepository) CreateAgent(ctx context.Context, agent *storage.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", ctx, agent)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentRepositoryMockRecorder) CreateAgent(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockAgentRepository)(nil).CreateAgent), ctx, agent)
}

// DeleteAgent mocks base method.
func (m *MockAgentRepository) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAgent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAgent indicates an expected call of DeleteAgent.
func (mr *MockAgentRepositoryMockRecorder) DeleteAgent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAgent", reflect.TypeOf((*MockAgentRepository)(nil).DeleteAgent), ctx, id)
}

// GetAgentByID mocks base method.
func (m *MockAgentRepository) GetAgentByID(ctx context.Context, id uuid.UUID) (*storage.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentByID", ctx, id)
	ret0, _ := ret[0].(*storage.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentByID indicates an expected call of GetAgentByID.
func (mr *MockAgentRepositoryMockRecorder) GetAgentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentByID", reflect.TypeOf((*MockAgentRepository)(nil).GetAgentByID), ctx, id)
}

// ListAgents mocks base method.
func (m *MockAgentRepository) ListAgents(ctx context.Context) ([]*storage.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", ctx)
	ret0, _ := ret[0].([]*storage.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockAgentRepositoryMockRecorder) ListAgents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockAgentRepository)(nil).ListAgents), ctx)
}

// ListAgentsByStatus mocks base method.
func (m *MockAgentRepository) ListAgentsByStatus(ctx context.Context, status storage.AgentStatus) ([]*storage.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentsByStatus", ctx, status)
	ret0, _ := ret[0].([]*storage.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentsByStatus indicates an expected call of ListAgentsByStatus.
func (mr *MockAgentRepositoryMockRecorder) ListAgentsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentsByStatus", reflect.TypeOf((*MockAgentRepository)(nil).ListAgentsByStatus), ctx, status)
}

// SetOfflineStatusForInactiveAgents mocks base method.
func (m *MockAgentRepository) SetOfflineStatusForInactiveAgents(ctx context.Context, inactiveThreshold time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOfflineStatusForInactiveAgents", ctx, inactiveThreshold)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOfflineStatusForInactiveAgents indicates an expected call of SetOfflineStatusForInactiveAgents.
func (mr *MockAgentRepositoryMockRecorder) SetOfflineStatusForInactiveAgents(ctx, inactiveThreshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOfflineStatusForInactiveAgents", reflect.TypeOf((*MockAgentRepository)(nil).SetOfflineStatusForInactiveAgents), ctx, inactiveThreshold)
}

// UpdateAgentStatus mocks base method.
func (m *MockAgentRepository) UpdateAgentStatus(ctx context.Context, id uuid.UUID, status storage.AgentStatus, lastHeartbeat time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentStatus", ctx, id, status, lastHeartbeat)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentStatus indicates an expected call of UpdateAgentStatus.
func (mr *MockAgentRepositoryMockRecorder) UpdateAgentStatus(ctx, id, status, lastHeartbeat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentStatus", reflect.TypeOf((*MockAgentRepository)(nil).UpdateAgentStatus), ctx, id, status, lastHeartbeat)
}

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskRepository) CreateTask(ctx context.Context, task *storage.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepository)(nil).CreateTask), ctx, task)
}

// CreateTaskResult mocks base method.
func (m *MockTaskRepository) CreateTaskResult(ctx context.Context, result *storage.TaskResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskResult indicates an expected call of CreateTaskResult.
func (mr *MockTaskRepositoryMockRecorder) CreateTaskResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskResult", reflect.TypeOf((*MockTaskRepository)(nil).CreateTaskResult), ctx, result)
}

// GetPendingTasksByAgent mocks base method.
func (m *MockTaskRepository) GetPendingTasksByAgent(ctx context.Context, agentID uuid.UUID) ([]*storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTasksByAgent", ctx, agentID)
	ret0, _ := ret[0].([]*storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTasksByAgent indicates an expected call of GetPendingTasksByAgent.
func (mr *MockTaskRepositoryMockRecorder) GetPendingTasksByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTasksByAgent", reflect.TypeOf((*MockTaskRepository)(nil).GetPendingTasksByAgent), ctx, agentID)
}

// GetScheduledTasks mocks base method.
func (m *MockTaskRepository) GetScheduledTasks(ctx context.Context) ([]storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledTasks", ctx)
	ret0, _ := ret[0].([]storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledTasks indicates an expected call of GetScheduledTasks.
func (mr *MockTaskRepositoryMockRecorder) GetScheduledTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledTasks", reflect.TypeOf((*MockTaskRepository)(nil).GetScheduledTasks), ctx)
}

// GetTaskByID mocks base method.
func (m *MockTaskRepository) GetTaskByID(ctx context.Context, taskID uuid.UUID) (*storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID)
	ret0, _ := ret[0].(*storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByID), ctx, taskID)
}

// GetTaskResultByTaskID mocks base method.
func (m *MockTaskRepository) GetTaskResultByTaskID(ctx context.Context, taskID uuid.UUID) (*storage.TaskResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskResultByTaskID", ctx, taskID)
	ret0, _ := ret[0].(*storage.TaskResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskResultByTaskID indicates an expected call of GetTaskResultByTaskID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskResultByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskResultByTaskID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskResultByTaskID), ctx, taskID)
}

// GetTasksByPrerequisite mocks base method.
func (m *MockTaskRepository) GetTasksByPrerequisite(ctx context.Context, prerequisiteID uuid.UUID) ([]storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByPrerequisite", ctx, prerequisiteID)
	ret0, _ := ret[0].([]storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByPrerequisite indicates an expected call of GetTasksByPrerequisite.
func (mr *MockTaskRepositoryMockRecorder) GetTasksByPrerequisite(ctx, prerequisiteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByPrerequisite", reflect.TypeOf((*MockTaskRepository)(nil).GetTasksByPrerequisite), ctx, prerequisiteID)
}

// ListTasks mocks base method.
func (m *MockTaskRepository) ListTasks(ctx context.Context) ([]*storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx)
	ret0, _ := ret[0].([]*storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTaskRepositoryMockRecorder) ListTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTaskRepository)(nil).ListTasks), ctx)
}

// ListTasksByAgentID mocks base method.
func (m *MockTaskRepository) ListTasksByAgentID(ctx context.Context, agentID uuid.UUID) ([]*storage.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasksByAgentID", ctx, agentID)
	ret0, _ := ret[0].([]*storage.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasksByAgentID indicates an expected call of ListTasksByAgentID.
func (mr *MockTaskRepositoryMockRecorder) ListTasksByAgentID(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasksByAgentID", reflect.TypeOf((*MockTaskRepository)(nil).ListTasksByAgentID), ctx, agentID)
}

// UpdateTaskSchedule mocks base method.
func (m *MockTaskRepository) UpdateTaskSchedule(ctx context.Context, taskID uuid.UUID, scheduleType sql.NullString, scheduledAt sql.NullTime, cronExpression sql.NullString, prerequisiteTaskID uuid.NullUUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskSchedule", ctx, taskID, scheduleType, scheduledAt, cronExpression, prerequisiteTaskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskSchedule indicates an expected call of UpdateTaskSchedule.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskSchedule(ctx, taskID, scheduleType, scheduledAt, cronExpression, prerequisiteTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskSchedule", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskSchedule), ctx, taskID, scheduleType, scheduledAt, cronExpression, prerequisiteTaskID)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepository) UpdateTaskStatus(ctx context.Context, taskID uuid.UUID, status storage.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, taskID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatus(ctx, taskID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatus), ctx, taskID, status)
}

// UpdateTaskStatusIfCurrent mocks base method.
func (m *MockTaskRepository) UpdateTaskStatusIfCurrent(ctx context.Context, taskID uuid.UUID, currentStatus, newStatus storage.TaskStatus) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatusIfCurrent", ctx, taskID, currentStatus, newStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatusIfCurrent indicates an expected call of UpdateTaskStatusIfCurrent.
func (mr *MockTaskRepositoryMockRecorder) UpdateTaskStatusIfCurrent(ctx, taskID, currentStatus, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatusIfCurrent", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTaskStatusIfCurrent), ctx, taskID, currentStatus, newStatus)
}

// MockLogRepository is a mock of LogRepository interface.
type MockLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryMockRecorder
	isgomock struct{}
}

// MockLogRepositoryMockRecorder is the mock recorder for MockLogRepository.
type MockLogRepositoryMockRecorder struct {
	mock *MockLogRepository
}

// NewMockLogRepository creates a new mock instance.
func NewMockLogRepository(ctrl *gomock.Controller) *MockLogRepository {
	mock := &MockLogRepository{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepository) EXPECT() *MockLogRepositoryMockRecorder {
	return m.recorder
}

// CreateLogEntries mocks base method.
func (m *MockLogRepository) CreateLogEntries(ctx context.Context, logs []*storage.Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogEntries", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLogEntries indicates an expected call of CreateLogEntries.
func (mr *MockLogRepositoryMockRecorder) CreateLogEntries(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogEntries", reflect.TypeOf((*MockLogRepository)(nil).CreateLogEntries), ctx, logs)
}

// GetLogsByTaskID mocks base method.
func (m *MockLogRepository) GetLogsByTaskID(ctx context.Context, taskID uuid.UUID) ([]*storage.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogsByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]*storage.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogsByTaskID indicates an expected call of GetLogsByTaskID.
func (mr *MockLogRepositoryMockRecorder) GetLogsByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogsByTaskID", reflect.TypeOf((*MockLogRepository)(nil).GetLogsByTaskID), ctx, taskID)
}

// MockMetricRepository is a mock of MetricRepository interface.
type MockMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricRepositoryMockRecorder is the mock recorder for MockMetricRepository.
type MockMetricRepositoryMockRecorder struct {
	mock *MockMetricRepository
}

// NewMockMetricRepository creates a new mock instance.
func NewMockMetricRepository(ctrl *gomock.Controller) *MockMetricRepository {
	mock := &MockMetricRepository{ctrl: ctrl}
	mock.recorder = &MockMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricRepository) EXPECT() *MockMetricRepositoryMockRecorder {
	return m.recorder
}

// GetMetricsByAgentID mocks base method.
func (m *MockMetricRepository) GetMetricsByAgentID(ctx context.Context, agentID uuid.UUID, since time.Time) ([]*storage.AgentMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsByAgentID", ctx, agentID, since)
	ret0, _ := ret[0].([]*storage.AgentMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricsByAgentID indicates an expected call of GetMetricsByAgentID.
func (mr *MockMetricRepositoryMockRecorder) GetMetricsByAgentID(ctx, agentID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsByAgentID", reflect.TypeOf((*MockMetricRepository)(nil).GetMetricsByAgentID), ctx, agentID, since)
}

// StoreAgentMetric mocks base method.
func (m *MockMetricRepository) StoreAgentMetric(ctx context.Context, metric *storage.AgentMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAgentMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAgentMetric indicates an expected call of StoreAgentMetric.
func (mr *MockMetricRepositoryMockRecorder) StoreAgentMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAgentMetric", reflect.TypeOf((*MockMetricRepository)(nil).StoreAgentMetric), ctx, metric)
}

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CreateNotificationDelivery mocks base method.
func (m *MockNotificationRepository) CreateNotificationDelivery(ctx context.Context, delivery *storage.NotificationDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationDelivery", ctx, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotificationDelivery indicates an expected call of CreateNotificationDelivery.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotificationDelivery(ctx, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationDelivery", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotificationDelivery), ctx, delivery)
}

// CreateNotificationEvent mocks base method.
func (m *MockNotificationRepository) CreateNotificationEvent(ctx context.Context, event *storage.NotificationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotificationEvent indicates an expected call of CreateNotificationEvent.
func (mr *MockNotificationRepositoryMockRecorder) CreateNotificationEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationEvent", reflect.TypeOf((*MockNotificationRepository)(nil).CreateNotificationEvent), ctx, event)
}

// FindLatestNotificationEventByDedupKeySince mocks base method.
func (m *MockNotificationRepository) FindLatestNotificationEventByDedupKeySince(ctx context.Context, dedupKey string, since time.Time, excludeID uuid.UUID) (*storage.NotificationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestNotificationEventByDedupKeySince", ctx, dedupKey, since, excludeID)
	ret0, _ := ret[0].(*storage.NotificationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestNotificationEventByDedupKeySince indicates an expected call of FindLatestNotificationEventByDedupKeySince.
func (mr *MockNotificationRepositoryMockRecorder) FindLatestNotificationEventByDedupKeySince(ctx, dedupKey, since, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestNotificationEventByDedupKeySince", reflect.TypeOf((*MockNotificationRepository)(nil).FindLatestNotificationEventByDedupKeySince), ctx, dedupKey, since, excludeID)
}

// GetNotificationDeliveryByID mocks base method.
func (m *MockNotificationRepository) GetNotificationDeliveryByID(ctx context.Context, id uuid.UUID) (*storage.NotificationDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationDeliveryByID", ctx, id)
	ret0, _ := ret[0].(*storage.NotificationDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationDeliveryByID indicates an expected call of GetNotificationDeliveryByID.
func (mr *MockNotificationRepositoryMockRecorder) GetNotificationDeliveryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationDeliveryByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetNotificationDeliveryByID), ctx, id)
}

// GetNotificationEventByID mocks base method.
func (m *MockNotificationRepository) GetNotificationEventByID(ctx context.Context, id uuid.UUID) (*storage.NotificationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationEventByID", ctx, id)
	ret0, _ := ret[0].(*storage.NotificationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationEventByID indicates an expected call of GetNotificationEventByID.
func (mr *MockNotificationRepositoryMockRecorder) GetNotificationEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationEventByID", reflect.TypeOf((*MockNotificationRepository)(nil).GetNotificationEventByID), ctx, id)
}

// ListNotificationDeliveriesByEventID mocks base method.
func (m *MockNotificationRepository) ListNotificationDeliveriesByEventID(ctx context.Context, eventID uuid.UUID) ([]*storage.NotificationDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationDeliveriesByEventID", ctx, eventID)
	ret0, _ := ret[0].([]*storage.NotificationDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationDeliveriesByEventID indicates an expected call of ListNotificationDeliveriesByEventID.
func (mr *MockNotificationRepositoryMockRecorder) ListNotificationDeliveriesByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationDeliveriesByEventID", reflect.TypeOf((*MockNotificationRepository)(nil).ListNotificationDeliveriesByEventID), ctx, eventID)
}

// ListNotificationDeliveriesForDispatch mocks base method.
func (m *MockNotificationRepository) ListNotificationDeliveriesForDispatch(ctx context.Context, now time.Time, limit int) ([]*storage.NotificationDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationDeliveriesForDispatch", ctx, now, limit)
	ret0, _ := ret[0].([]*storage.NotificationDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationDeliveriesForDispatch indicates an expected call of ListNotificationDeliveriesForDispatch.
func (mr *MockNotificationRepositoryMockRecorder) ListNotificationDeliveriesForDispatch(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationDeliveriesForDispatch", reflect.TypeOf((*MockNotificationRepository)(nil).ListNotificationDeliveriesForDispatch), ctx, now, limit)
}

// ListNotificationEvents mocks base method.
func (m *MockNotificationRepository) ListNotificationEvents(ctx context.Context, limit int) ([]*storage.NotificationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationEvents", ctx, limit)
	ret0, _ := ret[0].([]*storage.NotificationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationEvents indicates an expected call of ListNotificationEvents.
func (mr *MockNotificationRepositoryMockRecorder) ListNotificationEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationEvents", reflect.TypeOf((*MockNotificationRepository)(nil).ListNotificationEvents), ctx, limit)
}

// ListNotificationEventsByTaskID mocks base method.
func (m *MockNotificationRepository) ListNotificationEventsByTaskID(ctx context.Context, taskID uuid.UUID) ([]*storage.NotificationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationEventsByTaskID", ctx, taskID)
	ret0, _ := ret[0].([]*storage.NotificationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationEventsByTaskID indicates an expected call of ListNotificationEventsByTaskID.
func (mr *MockNotificationRepositoryMockRecorder) ListNotificationEventsByTaskID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationEventsByTaskID", reflect.TypeOf((*MockNotificationRepository)(nil).ListNotificationEventsByTaskID), ctx, taskID)
}

// ScheduleNotificationDeliveryRetry mocks base method.
func (m *MockNotificationRepository) ScheduleNotificationDeliveryRetry(ctx context.Context, id uuid.UUID, maxAttempts int32, nextRetryAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleNotificationDeliveryRetry", ctx, id, maxAttempts, nextRetryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScheduleNotificationDeliveryRetry indicates an expected call of ScheduleNotificationDeliveryRetry.
func (mr *MockNotificationRepositoryMockRecorder) ScheduleNotificationDeliveryRetry(ctx, id, maxAttempts, nextRetryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleNotificationDeliveryRetry", reflect.TypeOf((*MockNotificationRepository)(nil).ScheduleNotificationDeliveryRetry), ctx, id, maxAttempts, nextRetryAt)
}

// UpdateNotificationDeliveryStatus mocks base method.
func (m *MockNotificationRepository) UpdateNotificationDeliveryStatus(ctx context.Context, id uuid.UUID, attempt int32, status storage.NotificationDeliveryStatus, providerMessageID sql.NullString, providerResponseJSON []byte, errorMessage sql.NullString, lastErrorCode sql.NullString, sentAt sql.NullTime, nextRetryAt sql.NullTime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationDeliveryStatus", ctx, id, attempt, status, providerMessageID, providerResponseJSON, errorMessage, lastErrorCode, sentAt, nextRetryAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationDeliveryStatus indicates an expected call of UpdateNotificationDeliveryStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateNotificationDeliveryStatus(ctx, id, attempt, status, providerMessageID, providerResponseJSON, errorMessage, lastErrorCode, sentAt, nextRetryAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationDeliveryStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateNotificationDeliveryStatus), ctx, id, attempt, status, providerMessageID, providerResponseJSON, errorMessage, lastErrorCode, sentAt, nextRetryAt)
}

// UpdateNotificationEventStatus mocks base method.
func (m *MockNotificationRepository) UpdateNotificationEventStatus(ctx context.Context, id uuid.UUID, status storage.NotificationEventStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationEventStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationEventStatus indicates an expected call of UpdateNotificationEventStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateNotificationEventStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationEventStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateNotificationEventStatus), ctx, id, status)
}
