// protos/task.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: task.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_EXEC_COMMAND       TaskType = 0
	TaskType_EXEC_PYTHON_SCRIPT TaskType = 1
	TaskType_FETCH_FILE         TaskType = 2 // Агент скачивает файл с сервера
	TaskType_PUSH_FILE          TaskType = 3 // Агент отправляет файл на сервер
	TaskType_AGENT_UPDATE       TaskType = 4
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "EXEC_COMMAND",
		1: "EXEC_PYTHON_SCRIPT",
		2: "FETCH_FILE",
		3: "PUSH_FILE",
		4: "AGENT_UPDATE",
	}
	TaskType_value = map[string]int32{
		"EXEC_COMMAND":       0,
		"EXEC_PYTHON_SCRIPT": 1,
		"FETCH_FILE":         2,
		"PUSH_FILE":          3,
		"AGENT_UPDATE":       4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type TaskAcknowledgementStatus int32

const (
	TaskAcknowledgementStatus_RECEIVED   TaskAcknowledgementStatus = 0
	TaskAcknowledgementStatus_PROCESSING TaskAcknowledgementStatus = 1
	TaskAcknowledgementStatus_ERROR      TaskAcknowledgementStatus = 2
)

// Enum value maps for TaskAcknowledgementStatus.
var (
	TaskAcknowledgementStatus_name = map[int32]string{
		0: "RECEIVED",
		1: "PROCESSING",
		2: "ERROR",
	}
	TaskAcknowledgementStatus_value = map[string]int32{
		"RECEIVED":   0,
		"PROCESSING": 1,
		"ERROR":      2,
	}
)

func (x TaskAcknowledgementStatus) Enum() *TaskAcknowledgementStatus {
	p := new(TaskAcknowledgementStatus)
	*p = x
	return p
}

func (x TaskAcknowledgementStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskAcknowledgementStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[1].Descriptor()
}

func (TaskAcknowledgementStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[1]
}

func (x TaskAcknowledgementStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskAcknowledgementStatus.Descriptor instead.
func (TaskAcknowledgementStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

type GetTaskPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskPackageRequest) Reset() {
	*x = GetTaskPackageRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskPackageRequest) ProtoMessage() {}

func (x *GetTaskPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskPackageRequest.ProtoReflect.Descriptor instead.
func (*GetTaskPackageRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskPackageRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type TaskCommand struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=agent_management.TaskType" json:"task_type,omitempty"`
	Command  string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // Для EXEC_COMMAND
	Args     []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`       // Для EXEC_COMMAND
	// Поле script_content (5) удалено
	SourcePath       string `protobuf:"bytes,6,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	DestinationPath  string `protobuf:"bytes,7,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	TimeoutSeconds   int32  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	EntrypointScript string `protobuf:"bytes,9,opt,name=entrypoint_script,json=entrypointScript,proto3" json:"entrypoint_script,omitempty"` // Для EXEC_PYTHON_SCRIPT, указывает на главный файл в пакете
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskCommand) Reset() {
	*x = TaskCommand{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommand) ProtoMessage() {}

func (x *TaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommand.ProtoReflect.Descriptor instead.
func (*TaskCommand) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCommand) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCommand) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_EXEC_COMMAND
}

func (x *TaskCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TaskCommand) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *TaskCommand) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *TaskCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskCommand) GetEntrypointScript() string {
	if x != nil {
		return x.EntrypointScript
	}
	return ""
}

type TaskAcknowledgement struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TaskId        string                    `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskAcknowledgementStatus `protobuf:"varint,2,opt,name=status,proto3,enum=agent_management.TaskAcknowledgementStatus" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAcknowledgement) Reset() {
	*x = TaskAcknowledgement{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAcknowledgement) ProtoMessage() {}

func (x *TaskAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAcknowledgement.ProtoReflect.Descriptor instead.
func (*TaskAcknowledgement) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskAcknowledgement) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAcknowledgement) GetStatus() TaskAcknowledgementStatus {
	if x != nil {
		return x.Status
	}
	return TaskAcknowledgementStatus_RECEIVED
}

func (x *TaskAcknowledgement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x10agent_management\"0\n" +
	"\x15GetTaskPackageRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"%\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\xaf\x02\n" +
	"\vTaskCommand\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x127\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x1a.agent_management.TaskTypeR\btaskType\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x1f\n" +
	"\vsource_path\x18\x06 \x01(\tR\n" +
	"sourcePath\x12)\n" +
	"\x10destination_path\x18\a \x01(\tR\x0fdestinationPath\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11entrypoint_script\x18\t \x01(\tR\x10entrypointScript\"\x8d\x01\n" +
	"\x13TaskAcknowledgement\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2+.agent_management.TaskAcknowledgementStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*e\n" +
	"\bTaskType\x12\x10\n" +
	"\fEXEC_COMMAND\x10\x00\x12\x16\n" +
	"\x12EXEC_PYTHON_SCRIPT\x10\x01\x12\x0e\n" +
	"\n" +
	"FETCH_FILE\x10\x02\x12\r\n" +
	"\tPUSH_FILE\x10\x03\x12\x10\n" +
	"\fAGENT_UPDATE\x10\x04*D\n" +
	"\x19TaskAcknowledgementStatus\x12\f\n" +
	"\bRECEIVED\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022\xc0\x01\n" +
	"\vTaskService\x12W\n" +
	"\vAssignTasks\x12%.agent_management.TaskAcknowledgement\x1a\x1d.agent_management.TaskCommand(\x010\x01\x12X\n" +
	"\x0eGetTaskPackage\x12'.agent_management.GetTaskPackageRequest\x1a\x1b.agent_management.FileChunk0\x01B*Z(github.com/your_org/agent-management/apib\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_task_proto_goTypes = []any{
	(TaskType)(0),                  // 0: agent_management.TaskType
	(TaskAcknowledgementStatus)(0), // 1: agent_management.TaskAcknowledgementStatus
	(*GetTaskPackageRequest)(nil),  // 2: agent_management.GetTaskPackageRequest
	(*FileChunk)(nil),              // 3: agent_management.FileChunk
	(*TaskCommand)(nil),            // 4: agent_management.TaskCommand
	(*TaskAcknowledgement)(nil),    // 5: agent_management.TaskAcknowledgement
}
var file_task_proto_depIdxs = []int32{
	0, // 0: agent_management.TaskCommand.task_type:type_name -> agent_management.TaskType
	1, // 1: agent_management.TaskAcknowledgement.status:type_name -> agent_management.TaskAcknowledgementStatus
	5, // 2: agent_management.TaskService.AssignTasks:input_type -> agent_management.TaskAcknowledgement
	2, // 3: agent_management.TaskService.GetTaskPackage:input_type -> agent_management.GetTaskPackageRequest
	4, // 4: agent_management.TaskService.AssignTasks:output_type -> agent_management.TaskCommand
	3, // 5: agent_management.TaskService.GetTaskPackage:output_type -> agent_management.FileChunk
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
